#ORIGINAL                                   
 CLOF Algorithm -
1. Clustering
2. Outlier Set
3. LOF
*Large Data Set with More Complexity*
#VERSION 1
 P-CLOF Algorithm -
1. PCA
2. Clustering
3. Outlier Set
4. LOF
*Complexity reduced but includes False Positives*
#VERSION 2
 P-CLOF Algorithm with SVM -
1. PCA
2. Clustering
3. Outlier Set
4. LOF
*Expected Reduction in False Positives*
#VERSION 3
1. PCA
2. Ensemble Learning
2. Clustering
3. Outlier Set
4. LOF

# PROPER CLUSTERING ON INTERPOLATED DATA
#NUMBER of CLUSTERS 5


In [ ]:
#KMEANS CLUSTERING
import pandas as pd
from sklearn.cluster import KMeans
import matplotlib.pyplot as plt

# CLUSTERING ON 2D data which is obtained by minimal values+interpolation+PCA

# LOF

In [ ]:
import pandas as pd
import numpy as np
lof_df=pd.read_csv('small clusters as outliers.csv')
# CLUSTER CENTERS ARE [[ 4.49070588e+01  2.34421176e+01  4.00000000e+00]
# [ 1.58000000e+03 -4.14000000e+02  1.00000000e+00]
# [ 7.56000000e+02  4.38000000e+02  3.00000000e+00]
# [-9.92659691e-01 -3.29849239e-01  1.63064007e-15]
# [ 3.00833333e+02  1.04683333e+02  2.00000000e+00]] '''

In [ ]:
lof_df

Principal Component 1  Principal Component 2  cluster_label
0                   -0.8430                 -0.222              0
1                   -1.1600                 -0.400              0
2                    0.0441                  0.902              0
3                   -0.8260                 -0.565              0
4                   -2.0000                 -0.920              0
...                     ...                    ...            ...
8022               434.0000                 99.000              2
8023               337.0000                 88.500              2
8024               337.0000                240.000              2
8025               194.0000                 49.300              2
8026               756.0000                438.000              3

[8027 rows x 3 columns]

In [ ]:
# Step 1: Divide data into subsets
num_subsets = 2
subset_size = len(lof_df) // num_subsets
subsets = [lof_df[i*subset_size:(i+1)*subset_size] for i in range(num_subsets)]

In [ ]:
# Print the subsets
for i, subset in enumerate(subsets):
    print(f"Subset {i+1}:")
    print(subset)

Subset 1:
      Principal Component 1  Principal Component 2  cluster_label
0                   -0.8430                -0.2220              0
1                   -1.1600                -0.4000              0
2                    0.0441                 0.9020              0
3                   -0.8260                -0.5650              0
4                   -2.0000                -0.9200              0
...                     ...                    ...            ...
4008                -2.0200                -0.9380              0
4009                -2.2200                -1.0900              0
4010                -1.3200                -0.1950              0
4011                -1.1100                 0.5010              0
4012                -1.1600                -0.0836              0

[4013 rows x 3 columns]
Subset 2:
      Principal Component 1  Principal Component 2  cluster_label
4013                  0.961                 -0.707              0
4014                 -2.190    

In [ ]:
# Print a specific subset
subset_index = 0  # Change this to the index of the subset you want to print
print(f"Subset {subset_index + 1}:")
subset1 = subsets[subset_index]
print(subset1)
subset1.to_csv('subset1.csv', index=False)

Subset 1:
      Principal Component 1  Principal Component 2  cluster_label
0                   -0.8430                -0.2220              0
1                   -1.1600                -0.4000              0
2                    0.0441                 0.9020              0
3                   -0.8260                -0.5650              0
4                   -2.0000                -0.9200              0
...                     ...                    ...            ...
4008                -2.0200                -0.9380              0
4009                -2.2200                -1.0900              0
4010                -1.3200                -0.1950              0
4011                -1.1100                 0.5010              0
4012                -1.1600                -0.0836              0

[4013 rows x 3 columns]


In [ ]:
y_1 = pd.read_csv("subset1.csv")   #y1 means subset 1
y_1

Principal Component 1  Principal Component 2  cluster_label
0                   -0.8430                -0.2220              0
1                   -1.1600                -0.4000              0
2                    0.0441                 0.9020              0
3                   -0.8260                -0.5650              0
4                   -2.0000                -0.9200              0
...                     ...                    ...            ...
4008                -2.0200                -0.9380              0
4009                -2.2200                -1.0900              0
4010                -1.3200                -0.1950              0
4011                -1.1100                 0.5010              0
4012                -1.1600                -0.0836              0

[4013 rows x 3 columns]

In [ ]:
import pandas as pd
# Print a specific subset
subset_index = 1  # Change this to the index of the subset you want to print
print(f"Subset {subset_index + 1}:")
subset2 = subsets[subset_index]

subset2.to_csv('subset2.csv', index=False)

Subset 2:


In [ ]:
x_2 = pd.read_csv("subset2.csv")
x_2

Principal Component 1  Principal Component 2  cluster_label
0                     0.961                 -0.707              0
1                    -2.190                 -1.050              0
2                     1.110                  0.128              0
3                    -1.680                 -0.828              0
4                    -2.040                 -0.589              0
...                     ...                    ...            ...
4008                175.000                135.000              2
4009                434.000                 99.000              2
4010                337.000                 88.500              2
4011                337.000                240.000              2
4012                194.000                 49.300              2

[4013 rows x 3 columns]

In [ ]:
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import LocalOutlierFactor

# Standardize features for LOF (recommended)
scaler = StandardScaler()
scaled_features = scaler.fit_transform(y_1[['Principal Component 1', 'Principal Component 2']])

# Define LOF parameters (adjust based on your needs)
n_neighbors = 2  # Number of neighbors to consider
contamination = 0.01 # Expected proportion of outliers

# Create LOF object and fit it
lof = LocalOutlierFactor(n_neighbors=n_neighbors, contamination=contamination)
lof_scores = lof.fit_predict(scaled_features)

# Identify outlier indices
outlier_indices = np.where(lof_scores == -1)[0]  # -1 indicates outliers

# Sort outlier indices by LOF scores in descending order
sorted_outlier_indices = outlier_indices[np.argsort(lof_scores[outlier_indices])[::-1]]

# Rank outliers based on their LOF scores
outlier_ranks = range(1, len(sorted_outlier_indices) + 1)

# DataFrame with outlier information
outlier_df_1 = pd.DataFrame({
    'Index': sorted_outlier_indices,
    'LOF Score': lof_scores[sorted_outlier_indices],
    'Rank': outlier_ranks
})

print(outlier_df_1)


    Index  LOF Score  Rank
0    3898         -1     1
1    2028         -1     2
2    1975         -1     3
3    1841         -1     4
4    1457         -1     5
5    1448         -1     6
6    1359         -1     7
7    1356         -1     8
8    1264         -1     9
9    1250         -1    10
10   1244         -1    11
11   1157         -1    12
12    925         -1    13
13    904         -1    14
14    743         -1    15
15    602         -1    16
16    476         -1    17
17    432         -1    18
18     50         -1    19
19   1993         -1    20
20   2097         -1    21
21   3806         -1    22
22   2218         -1    23
23   3734         -1    24
24   3723         -1    25
25   3711         -1    26
26   3678         -1    27
27   3480         -1    28
28   3479         -1    29
29   3277         -1    30
30   3155         -1    31
31   3128         -1    32
32   3085         -1    33
33   2760         -1    34
34   2541         -1    35
35   2497         -1    36
3

In [ ]:
outlier_df_1.to_csv('clof_outliers_y_1.csv', index=True)

In [ ]:
# Extract original data indices from outlier indices
outlier_indices_original = y_1.index[sorted_outlier_indices].tolist()


In [ ]:
# Access specific data points
outlier_data_1 = y_1.iloc[outlier_indices_original]

# Print or use the outlier data as needed
print(outlier_data_1)


      Principal Component 1  Principal Component 2  cluster_label
3898                 -2.550                 -1.280              0
2028                 -2.250                 -1.170              0
1975                 -2.470                 -1.250              0
1841                 -2.190                 -1.100              0
1457                 -2.240                 -1.130              0
1448                 -1.960                 -1.020              0
1359                 -2.510                 -1.250              0
1356                 -1.940                 -1.020              0
1264                 -2.480                 -1.240              0
1250                 -2.500                 -1.260              0
1244                 -2.000                 -1.060              0
1157                 -2.310                 -1.130              0
925                  -1.970                 -1.040              0
904                  -2.500                 -1.260              0
743       

In [ ]:
outlier_data_1.to_csv('index_and_pca_of_CLOF_outliers_y_1.csv', index=False)

In [ ]:
x_2A = pd.read_csv("subset2 (1).csv")
x_2A

Principal Component 1  Principal Component 2  cluster_label
0                     0.961                 -0.707              0
1                    -2.190                 -1.050              0
2                     1.110                  0.128              0
3                    -1.680                 -0.828              0
4                    -2.040                 -0.589              0
...                     ...                    ...            ...
4009                434.000                 99.000              2
4010                337.000                 88.500              2
4011                337.000                240.000              2
4012                194.000                 49.300              2
4013                756.000                438.000              3

[4014 rows x 3 columns]

In [ ]:
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import LocalOutlierFactor

# Standardize features for LOF (recommended)
scaler = StandardScaler()
scaled_features = scaler.fit_transform(x_2A[['Principal Component 1', 'Principal Component 2']])

# Define LOF parameters (adjust based on your needs)
n_neighbors = 2  # Number of neighbors to consider
contamination = 0.01  # Expected proportion of outliers

# Create LOF object and fit it
lof = LocalOutlierFactor(n_neighbors=n_neighbors, contamination=contamination)
lof_scores = lof.fit_predict(scaled_features)

# Identify outlier indices
outlier_indices = np.where(lof_scores == -1)[0]  # -1 indicates outliers

# Sort outlier indices by LOF scores in descending order
sorted_outlier_indices = outlier_indices[np.argsort(lof_scores[outlier_indices])[::-1]]

# Rank outliers based on their LOF scores
outlier_ranks = range(1, len(sorted_outlier_indices) + 1)

# DataFrame with outlier information
outlier_df_2 = pd.DataFrame({
    'Index': sorted_outlier_indices,
    'LOF Score': lof_scores[sorted_outlier_indices],
    'Rank': outlier_ranks
})

print(outlier_df_2)

    Index  LOF Score  Rank
0    3805         -1     1
1    1292         -1     2
2    1884         -1     3
3    1864         -1     4
4    1835         -1     5
5    1590         -1     6
6    1576         -1     7
7    1569         -1     8
8    1374         -1     9
9    1258         -1    10
10   3581         -1    11
11   1196         -1    12
12    967         -1    13
13    867         -1    14
14    800         -1    15
15    779         -1    16
16    624         -1    17
17    557         -1    18
18   1905         -1    19
19   1906         -1    20
20   2056         -1    21
21   2125         -1    22
22   3478         -1    23
23   3426         -1    24
24   3355         -1    25
25   3277         -1    26
26   3109         -1    27
27   3062         -1    28
28   3047         -1    29
29   3025         -1    30
30   3000         -1    31
31   2655         -1    32
32   2526         -1    33
33   2379         -1    34
34   2255         -1    35
35   2254         -1    36
3

In [ ]:
outlier_df_2.to_csv('clof_outliers_x_2A.csv', index=True)

In [ ]:
# Extract original data indices from outlier indices
outlier_indices_original = x_2A.index[sorted_outlier_indices].tolist()

In [ ]:
outlier_data_2.to_csv('index_and_pca_of_CLOF_outliers_x_2A.csv', index=False)

In [ ]:
final_lof_scores_sorted.to_csv('final_ensemble_of_subsets.csv', index=False)

In [ ]:
import pandas as pd
from sklearn.metrics import precision_score, recall_score, f1_score

# Read the dataset
data = pd.read_excel('Final_ensemble_of_subsets_with_flags.xlsx')  # Replace 'your_dataset.csv' with the actual file path

# Calculate True Positives (TP) and False Positives (FP)
TP = data[(data['Flag'] == 1) & (data['LOF Score'] == -1)].shape[0]
FP = data[(data['Flag'] == 0) & (data['LOF Score'] == -1)].shape[0]

# Calculate Accuracy
accuracy = TP / (TP + FP)

precision = TP / (TP + FP)

print("Precision:", precision)
print("True Positives:", TP)
print("False Positives:", FP)
print("Accuracy:", accuracy)


Precision: 0.8974358974358975
True Positives: 70
False Positives: 8
Accuracy: 0.8974358974358975
